version: '3.8'

services:
  web:
    build: .
    container_name: voting-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - SECRET_KEY=your_secret_key
      - ADMIN_PASSCODE=123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./src:/app
    networks:
      - voting-network

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - voting-network

networks:
  voting-network:
    driver: bridge

volumes:
  redis-data: