apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.flaskApp.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "flask-voting-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.flaskApp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.flaskApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.flaskApp.name }}
    spec:
      containers:
        - name: {{ .Values.flaskApp.name }}
          image: "{{ .Values.flaskApp.image.repository }}:{{ .Values.flaskApp.image.tag }}"
          imagePullPolicy: {{ .Values.flaskApp.image.pullPolicy }}
          ports:
            - containerPort: 5000
          resources:
            {{- toYaml .Values.flaskApp.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "flask-voting-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
    spec:
      containers:
        - name: {{ .Values.redis.name }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: 6379
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-redis-pvc
