apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "flask-voting-app.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.secretKey }}
  ADMIN_PASSCODE: {{ .Values.secrets.adminPasscode }}
